;creator=NiklasCFW
;version=1.0.0
;about='NiklasCFW Downloader'

[@NiklasCFW Downloader]

[Version]
;mode=table
;background=true
;gap=20
ini_file './include/updater/config.ini'
'Auf OmniNX Standard wechseln' = ''

[OmniNX - neuste]
try:
download https://git.niklascfw.de/api/v1/repos/OmniNX/OmniNX/releases?limit=1 /config/ultrahand/downloads/omninx-api.json
json_file /config/ultrahand/downloads/omninx-api.json
download {json_file(0,assets,2,browser_download_url)} /config/ultrahand/downloads/OmniNX.zip
unzip /config/ultrahand/downloads/OmniNX.zip /
delete /config/ultrahand/downloads/omninx-api.json
delete /config/ultrahand/downloads/OmniNX.zip
notify '{WARNING_SYMBOL} Führe in Hekate fort' 24

[Hinweis]
[Hinweis]
;mode=table
;background=true
;spacing=4
;gap=30
;alignment=left
;info_text_color=warning
'Dies ist das Ende vom NiklasCFW Pack.'
'Danke an jeden einzelnen da draußen, der'
'das Pack verwendet hat.'
'Mit OmniNX wird es noch größer.'
'Ab dem 30.06.2026 endet der Support'
'für das NiklasCFW Pack.'
''
'Weiter Infos findest du auf dem'
'NiklasCFW YouTube Kanal und auf'
'unserem Discord Server.'
''
'Bis dahin, viel Spaß mit OmniNX!'
